# Generated by Django 4.2.7 on 2023-11-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverificationlogs_passwordrecoverylogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='share_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
