# Generated by Django 4.2.7 on 2023-11-10 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('toro_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('energy_capacity', models.CharField(max_length=20)),
                ('energy_source', models.CharField(choices=[('tRR', 'transad'), ('sff', 'grests')], max_length=3)),
                ('location', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('imaage1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ProjectsImages',
            new_name='ProjectImage',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
