# Generated by Django 4.2.7 on 2023-11-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toro_market', '0002_project_rename_projectsimages_projectimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='imaage1',
            new_name='image1',
        ),
    ]
