# Generated by Django 4.2.7 on 2023-11-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toro_market', '0003_rename_imaage1_project_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project_content_type',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='project_object_id',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toro_market.project'),
        ),
    ]
