# Generated by Django 4.2.7 on 2023-11-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toro_market', '0008_alter_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
