# Generated by Django 4.2.7 on 2023-11-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toro_market', '0009_project_image1_project_image2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
