# Generated by Django 4.2.7 on 2023-11-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toro_market', '0011_transaction_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount_invested',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
