# Generated by Django 4.2.7 on 2023-11-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toro_market', '0013_transaction_business_alter_transaction_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount_invested',
            field=models.FloatField(default=0),
        ),
    ]
