# Generated by Django 4.2.7 on 2023-11-20 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toro_market', '0015_alter_investment_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_invested_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
